### ISSUE TITLE
Top event day header disappears when shared day items are loaded on top while loading indicator is present

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#132] opened 2017-03-03 13:45 UTC
Steps to reproduce:
- Find a event discover start day and time where there are events before that time on the same day (GK: I call it the _merging_ case)
- Start event list screen for that time
- After the first page is loaded, scroll up to see the loading indicator (either fully visible (case A) or partly visible (case B))
(Technical note: put a `Thread.sleep()` in `EventListDownloadTask#doInBackgroundWithException` for slowing down load)
- Expected:
The items for the same day are loaded and the day header jumps up to the top of the screen
- Actual:
The items for the same day are loaded correctly, but the day header disappears (if you scroll up it will be in its place above the first event for the day)

**Comment by lemonboston** [comment] 2017-03-03 13:48
Note: The trick applied to the "non-merging" scenario to disable and enable sticky headers when firstVisibleItemPosition == 0 works for case B, but not for case A.

**Comment by dmfs** [comment] 2017-04-18 13:39
Is this still an issue? I can't reproduce it.

**Comment by lemonboston** [comment] 2017-04-18 18:34
I just checked and I couldn't reproduce it either. Nice surprise :) Not sure what fixed it but I think we can close it now.

**Comment by dmfs** [comment] 2017-04-18 20:04
thx, closing this.

**Closed as completed by dmfs** 2017-04-18 20:04 UTC
Labels: live-bug
