### ISSUE TITLE
Enable hardware acceleration by default.

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#112] opened 2017-02-02 10:11 UTC
In order to get a smooth experience, as a user I want the SDK to use hardware acceleration whenever possible.

Some partner apps might have disabled HW acceleration by default. We'll enable it explicitly for our activities in the AndroidManifest.

**Comment by lemonboston** [comment] 2017-02-02 12:40
Duplicate of https://github.com/schedjoules/android-event-discovery-sdk/issues/92, I suppose that one can be closed.

**Comment by dmfs** [comment] 2017-02-02 13:05
Oh, yes of course. I'll close the other one.

**Closed as completed** 2017-02-06 13:08 UTC
Labels: maintenance, ad-hoc
