### ISSUE TITLE
update UI to show links to the "original" resources, if present

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#420] opened 2017-09-15 10:17 UTC
@dmfs commented on [Wed Apr 19 2017](https://github.com/schedjoules/general-issues/issues/182)

In order to get more information, as a user I want to see the original source of some event, like the ones from meetup or facebook.
---

In #181 the API will be updated to also include the "original" source of an event. If present, the UI should show this in a separate line.

**Comment by lemonboston** [comment] 2017-09-18 15:28
This is a sort of duplicate of: https://github.com/schedjoules/general-issues/issues/170

**Closed as completed** 2017-09-19 08:18 UTC
